name: Scheduled Jobs

on:
  schedule:
    - cron: '* * * * *'  # Runs every minute
  workflow_dispatch:     # Allows manual trigger

env:
  JOB_1_START_TIME: "15 21 * * *"
  JOB_2_START_TIME: "16 21 * * *"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check if it's time to run Job 1
        id: check_time
        run: |
          CURRENT_TIME=$(date -u +"%M %H * * *")
          echo "Current time: $CURRENT_TIME"
          if [ "$CURRENT_TIME" = "${{ env.JOB_1_START_TIME }}" ]; then
            echo "Run=1" >> $GITHUB_OUTPUT
          else
            echo "Run=0" >> $GITHUB_OUTPUT
          fi

      - name: Run Job 1
        if: steps.check_time.outputs.Run == '1'
        run: echo "Running Job 1 tasks..."

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Check if it's time to run Job 2
        id: check_time
        run: |
          CURRENT_TIME=$(date -u +"%M %H * * *")
          echo "Current time: $CURRENT_TIME"
          if [ "$CURRENT_TIME" = "${{ env.JOB_2_START_TIME }}" ]; then
            echo "Run=1" >> $GITHUB_OUTPUT
          else
            echo "Run=0" >> $GITHUB_OUTPUT
          fi

      - name: Run Job 2
        if: steps.check_time.outputs.Run == '1'
        run: echo "Running Job 2 tasks..."
