name: Two Independent Jobs

on:
  workflow_dispatch:
    inputs:
      TARGETTASKNAME:
        description: 'Which job to run manually (job1 or job2)'
        required: true
  schedule:
    - cron: '46 22 * * *'     # job1
    - cron: '48 22 * * *'     # job2

jobs:
  job1:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.TARGETTASKNAME == 'job1' || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Echo Job 1
        run: echo "Running Job 1"

  job2:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.TARGETTASKNAME == 'job2' || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Echo Job 2
        run: echo "Running Job 2"
