name: Three Jobs Workflow

on:
  schedule:
    - cron: '* * * * *'  # Every minute
  workflow_dispatch:
    inputs:
      TARGETTASKNAME:
        description: 'Name of the job to run manually (job1, job2, or job3)'
        required: false
        default: ''

jobs:
  job1:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.TARGETTASKNAME == 'job1')
    steps:
      - name: Print UTC time for job1
        run: |
          echo "Job1 UTC Time: $(date -u)"

  job2:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.TARGETTASKNAME == 'job2')
    steps:
      - name: Conditionally wait 15 minutes if scheduled
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            echo "Scheduled run: waiting 3 minutes..."
            sleep 180
          else
            echo "Manual run: skipping wait."
          fi
      - name: Print UTC time for job2
        run: |
          echo "Job2 UTC Time: $(date -u)"

  job3:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.TARGETTASKNAME == 'job3'
    steps:
      - name: Print UTC time for job3
        run: |
          echo "Job3 UTC Time: $(date -u)"
