name: Job 1 Only

on:
  schedule:
    - cron: '11 01 * * *'
  workflow_dispatch:
    inputs:
      TARGETTASKNAME:
        description: 'Run job1 manually'
        required: true

jobs:
  job1:
    if: github.event_name == 'schedule' || github.event.inputs.TARGETTASKNAME == 'job1'
    runs-on: ubuntu-latest
    steps:
      - name: Echo Job 1
        run: echo "Running Job 1"

      - name: Show current time
        run: |
          echo "Current UTC time (human-readable): $(date -u)"
          MIN=$(date -u +'%M')
          HOUR=$(date -u +'%H')
          echo "Current time in cron format: $MIN $HOUR * * *"
